{{- $kc := .Values.keycloak | default dict }}
{{- $operator := $kc.operator | default dict }}
{{- $crdReady := or (.Capabilities.APIVersions.Has "k8s.keycloak.org/v2alpha1") ($kc.forceRender | default false) }}
{{- $operatorInstall := ternary $operator.install true (hasKey $operator "install") }}
{{- if and ($kc.enabled | default false) $operatorInstall $crdReady }}
{{- $ns := include "aegis-services.keycloak.namespace" . }}
{{- $image := default "registry.redhat.io/rhbk/keycloak-rhel9-operator:26.2-11" $operator.image }}
{{- $keycloakImage := default "registry.redhat.io/rhbk/keycloak-rhel9:26.2-11" (default $operator.keycloakImage $operator.imageOverride) }}
{{- $imagePullPolicy := default "Always" $operator.imagePullPolicy }}
{{- $annotations := merge (dict "app.quarkus.io/quarkus-version" "3.27.0" "app.quarkus.io/vcs-uri" "https://github.com/keycloak/keycloak.git" "app.quarkus.io/build-timestamp" "2025-10-23 - 07:06:46 +0000") (default (dict) $operator.annotations) }}
{{- $resources := default (dict "limits" (dict "cpu" "700m" "memory" "450Mi") "requests" (dict "cpu" "300m" "memory" "450Mi")) $operator.resources }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak-operator
  namespace: {{ $ns }}
  labels:
    {{- include "aegis-services.keycloak.labels" . | nindent 4 }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keycloak-operator-clusterrole
  labels:
    app.kubernetes.io/name: keycloak-operator
rules:
  - apiGroups:
      - config.openshift.io
    resources:
      - ingresses
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keycloakrealmimportcontroller-cluster-role
  labels:
    app.kubernetes.io/name: keycloak-operator
rules:
  - apiGroups:
      - k8s.keycloak.org
    resources:
      - keycloakrealmimports
      - keycloakrealmimports/status
      - keycloakrealmimports/finalizers
    verbs:
      - get
      - list
      - watch
      - patch
      - update
      - create
      - delete
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keycloakcontroller-cluster-role
  labels:
    app.kubernetes.io/name: keycloak-operator
rules:
  - apiGroups:
      - k8s.keycloak.org
    resources:
      - keycloaks
      - keycloaks/status
      - keycloaks/finalizers
    verbs:
      - get
      - list
      - watch
      - patch
      - update
      - create
      - delete
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - networkpolicies
      - ingresses
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keycloak-operator-clusterrole-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keycloak-operator-clusterrole
subjects:
  - kind: ServiceAccount
    name: keycloak-operator
    namespace: {{ $ns }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keycloak-operator-role
  namespace: {{ $ns }}
  labels:
    app.kubernetes.io/name: keycloak-operator
rules:
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
      - services
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
    verbs:
      - list
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keycloak-operator-role-binding
  namespace: {{ $ns }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keycloak-operator-role
subjects:
  - kind: ServiceAccount
    name: keycloak-operator
    namespace: {{ $ns }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keycloakrealmimportcontroller-role-binding
  namespace: {{ $ns }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keycloakrealmimportcontroller-cluster-role
subjects:
  - kind: ServiceAccount
    name: keycloak-operator
    namespace: {{ $ns }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keycloakcontroller-role-binding
  namespace: {{ $ns }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keycloakcontroller-cluster-role
subjects:
  - kind: ServiceAccount
    name: keycloak-operator
    namespace: {{ $ns }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keycloak-operator-view
  namespace: {{ $ns }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: keycloak-operator
    namespace: {{ $ns }}
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-operator
  namespace: {{ $ns }}
  labels:
    {{- include "aegis-services.keycloak.labels" . | nindent 4 }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: keycloak-operator
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-operator
  namespace: {{ $ns }}
  labels:
    {{- include "aegis-services.keycloak.labels" . | nindent 4 }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: keycloak-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: keycloak-operator
        app.kubernetes.io/managed-by: quarkus
      annotations:
        {{- toYaml $annotations | nindent 8 }}
    spec:
      serviceAccountName: keycloak-operator
      {{- with $operator.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: keycloak-operator
          image: {{ $image }}
          imagePullPolicy: {{ $imagePullPolicy }}
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: RELATED_IMAGE_KEYCLOAK
              value: {{ $keycloakImage }}
            {{- with $operator.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /q/health/started
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          resources:
            {{- toYaml $resources | nindent 12 }}
{{- end }}
